### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: read_bytes(): Error reading byte in

### ISSUE THREAD

**Issue by barryvdh** [jaspervdm/pogoapi-php#4]
I was able to get the Endpoint yesterday, but seem to run into the same error now:

```
PHP Warning:  fread(): Length parameter must be greater than 0 in project/vendor/jaspervdm/pogoprotos-php/src/protocolbuffers.inc.php on line 304

Warning: fread(): Length parameter must be greater than 0 in project/vendor/jaspervdm/pogoprotos-php/src/protocolbuffers.inc.php on line 304
PHP Fatal error:  Uncaught Exception: read_bytes(): Error reading byte in project/vendor/jaspervdm/pogoprotos-php/src/protocolbuffers.inc.php:310
Stack trace:
#0 project/vendor/jaspervdm/pogoprotos-php/src/POGOProtos/Networking/Envelopes/ResponseEnvelope.proto.php(204): Protobuf::read_bytes(Resource id #63, 0, 0)
#1 project/vendor/jaspervdm/pogoprotos-php/src/protocolbuffers.inc.php(79): POGOProtos\Networking\Envelopes\ResponseEnvelope->read(Resource id #63, 0)
#2 project/vendor/jaspervdm/pogoprotos-php/src/POGOProtos/Networking/Envelopes/ResponseEnvelope.proto.php(136): ProtobufMessage->__construct('\x085\x10\xA4\xB5\x98\xDE\x01\x1A#pgore...', 0)
#3 pogoapi-php/src/Session/Session.php(130): POGOProtos\Networking\Envelopes\ResponseEnvelope->__construct('\x085\x10\xA4\xB5\x98\xDE\x01\x1A#pgore...')
#4 pogoapi-php/src/Session/Session.php(91): POGOAPI\Session\Session->req(Object(POGOProtos\Networking\Envelopes\RequestEnvelo in project/vendor/jaspervdm/pogoprotos-php/src/protocolbuffers.inc.php on line 310
```

String body dumped in CLI is:

```
string(141) 5????#pgorelease.nianticlabs.com/plfe/238:[
@??m6??m??5F?Qp?T/v???|Qdp??G???ߜ*:?'??)?$????w[FnH?J????*?L??ݺ
                                                               Q^P??p-?"
```

**Comment by jaspervdm** [comment]
I just noticed this as well. I will look into this either this evening or tomorrow evening.

**Comment by barryvdh** [comment]
Should be fixed with https://github.com/jaspervdm/pogoprotos-php/pull/4

**Comment by jaspervdm** [comment]
No longer relevant since the switch to different protobuf class generator
